site_name: A gentle introduction to actinia
site_url:  https://pages.gitlab.io/actinia-introduction
#site_url: https://namespace.gitlab.io
docs_dir:  docs
theme:     readthedocs
extra_css: [extra.css]
# https://github.com/mkdocs/mkdocs/issues/991
use_directory_urls: true
# use_directory_urls: false
# plugins:
#     - with-pdf
plugins:
    - external-markdown
nav:
    - 'index.md'
    - '2_concepts.md'
    - '3_explore.md'
    - '4_clients.md'
    - '5_excercises.md'
    - '6_conclusions.md'
    - 'about.md'
